/**
 * Created by user on 9/15/23.
 */

public with sharing class KPNConstants {

    /** Picklist values **/
    public static final String CONTRACT_STATUS_DRAFT = 'Draft';
    public static final String CONTRACT_STATUS_ACTIVATED = 'Activated';
    public static final String CONTRACT_STATUS_IN_APPROVAL_PROCESS = 'In Approval Process';
    public static final String ORDER_STATUS_DRAFT = 'Draft';
    public static final String ORDER_STATUS_ACTIVATED = 'Activated';
    public static final String ORDER_ITEM_STATUS_DRAFT = 'Draft';
    public static final String ORDER_ITEM_STATUS_ACTIVATED = 'Activated';

}
